language: perl
env:
  - IN_TRAVIS=1 AUTHOR_TESTING=1
perl:
  - "dev"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
matrix:
  allow_failures:
    - perl: dev
    - perl: "5.20"
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

